--- 
- hosts: all
  become: yes
  tasks:
  - package:
      name: epel-release
      state: present
    when: ansible_distribution == 'CentOS'
  - package:
      name: [ sl, cowsay ]
      state: present
  - lineinfile:
      path: /root/.bashrc
      line: '{{item}}'
    loop:
    - 'PATH=$PATH:/usr/games/'
    - 'alias ls="ls --color"'
...

